sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
install:
  - yarn
  - cd examples/jest && yarn && cd ../..
  - cd examples/cucumber && yarn && cd ../..
before_script:
  - jdk_switcher use oraclejdk8
  - java -version
  - google-chrome --product-version
script: 
  - yarn lint
  - yarn ci
  - cd examples/jest && yarn ci && cd ../..
  - cd examples/cucumber && yarn ci && cd ../..
cache:
  yarn: true
  directories:
    - node_modules
    - examples/jest/node_modules
    - examples/cucumber/node_modules
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
