language: node_js
node_js:
  - "8"
before_script:
  - jdk_switcher use oraclejdk8
script: yarn lint && yarn ci
cache:
  yarn: true
  directories:
    - "node_modules"
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
